# ASSIGNMENT 2 - Mohammed Raza Asfak Chidimar (MCS231004)

**Topic: Chapter 3 & Chapter 4**
- Due: 4th December 2023
- Mode: Individual Assignment
- Submission: E-Learning

### QUESTION 1


Given a raw data of the record of the attendance for 15 employees in a company for a 14 days event. The exported raw data is recorded in following way:

<br>
<center>Figure 1</center>
<img src="Figure 1.png", style="width: 350px";>

(i) Read the “Attendance_RAW.txt” and save the data into a NumPy array.

In [2]:
import numpy as np

file_path = "Attendance_RAW.txt"
attendance_data = np.genfromtxt(file_path, delimiter=',',dtype=str)
print(attendance_data)


['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1'
 '0' '0' '1' '1' '0' '1' '1' '0' '1' '1' '0' '1' '1' '1' '1' '0' '1' '1'
 '1' '1' '1' '0' '0' '0' '1' '1' '1' '1' '0' '0' '0' '0' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '0' '1' '1' '1' '0' '1' '1' '1' '1' '0' '0' '1'
 '1' '1' '0' '1' '1' '0' '1' '1' '0' '0' '1' '1' '1' '1' '1' '1' '1' '1'
 '0' '0' '1' '0' '0' '1' '1' '1' '1' '0' '1' '0' '1' '1' '0' '1' '1' '1'
 '0' '1' '0' '1' '0' '1' '1' '1' '1' '1' '1' '0' '1' '0' '0' '0' '0' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '0' '1' '1' '0' '0' '0' '0' '1' '1' '1' '1' '1' '1'
 '1' '1' '0' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '1' '0'
 '1' '1' '1' '0' '0' '0' '1' '0' '1' '1' '1' '1']


(ii) Shape the NumPy array to a structure where row represents the employees, column represents the working days.

In [3]:
num_employees = 15
num_days = 14
attendance_data = attendance_data.reshape(num_employees, num_days)
print(attendance_data)

[['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '0' '1' '0' '0' '1' '1' '0' '1']
 ['1' '0' '1' '1' '0' '1' '1' '1' '1' '0' '1' '1' '1' '1']
 ['1' '0' '0' '0' '1' '1' '1' '1' '0' '0' '0' '0' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '1' '1' '0' '1']
 ['1' '1' '1' '0' '0' '1' '1' '1' '0' '1' '1' '0' '1' '1']
 ['0' '0' '1' '1' '1' '1' '1' '1' '1' '1' '0' '0' '1' '0']
 ['0' '1' '1' '1' '1' '0' '1' '0' '1' '1' '0' '1' '1' '1']
 ['0' '1' '0' '1' '0' '1' '1' '1' '1' '1' '1' '0' '1' '0']
 ['0' '0' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0']
 ['1' '1' '0' '0' '0' '0' '1' '1' '1' '1' '1' '1' '1' '1']
 ['0' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1']
 ['1' '0' '1' '1' '1' '0' '0' '0' '1' '0' '1' '1' '1' '1']]


In [6]:
na = na.astype(int)
list_of_sum_all_column = np.sum(na, axis=0)
list_of_sum_all_column = list_of_sum_all_column.tolist()

array([ 9,  9, 11, 12, 11, 12, 13, 13, 11, 11, 11, 11, 12, 12])

(iii) Construct a function that can calculate and return the list of average of attendance for each day.

In [16]:
import numpy as np

def cal_average_attendance(attendance_data):
   
    attendance_data = attendance_data.astype(int)

    average_attendance_per_day = np.sum(attendance_data, axis=0)
    average_of_14_days = np.mean(average_attendance_per_day)

    return average_attendance_per_day.tolist(),average_of_14_days


attendance_per_day, average_attendance  = cal_average_attendance(attendance_data)
print(f"Attendance of each day : {attendance_per_day}")
print(f"Average Attendance of 14 days : {average_attendance}")




Attendance of each day : [9, 9, 11, 12, 11, 12, 13, 13, 11, 11, 11, 11, 12, 12]
Average Attendance of 14 days : 11.285714285714286


### QUESTION 2

(i) Create a NumPy array like below:

<br>
<img src="Output2.png", style="width: 200px", align="left";>

In [8]:
my_array = np.array([[33, 22, 11], [55, 66, 44], [99, 98, 77]])
print(my_array)



[[33 22 11]
 [55 66 44]
 [99 98 77]]


(ii) Sort the array given in ascending order.

In [9]:
sorted_array = np.sort(my_array)
print("Sorted Array in Ascending Order:")
print(sorted_array)


Sorted Array in Ascending Order:
[[11 22 33]
 [44 55 66]
 [77 98 99]]


(iii) Compute sum of all elements, sum of each column and sum of each row of the sorted array.

In [11]:
total_sum = np.sum(sorted_array)
print(total_sum)
column_sums = np.sum(sorted_array, axis=0)
print(column_sums)
row_sums = np.sum(sorted_array, axis=1)
print(row_sums)

505
[132 175 198]
[ 66 165 274]


(iv) Compute mean of all elements, mean of each column and mean of each row of the sorted array.



In [12]:
total_mean = np.mean(sorted_array)
column_means = np.mean(sorted_array, axis=0)
row_means = np.mean(sorted_array, axis=1)

print("Mean of all elements:", total_mean)
print(f"Mean of each column : {column_means}")
print(f"Mean of each row : {row_means}")

Mean of all elements: 56.111111111111114
Mean of each column : [44.         58.33333333 66.        ]
Mean of each row : [22.         55.         91.33333333]


(v) Compute cumulative sum of each column and cumulative product of each row of the given array.


In [14]:
colcumsum = np.cumsum(sorted_array, axis=0)
row_cumprod = np.cumprod(sorted_array, axis=1)

print(f"Cumulative Sum of Columns : \n{colcumsum}")
print(f"Cumulative Product of Rows : \n{row_cumprod}")

Cumulative Sum of Columns : 
[[ 11  22  33]
 [ 55  77  99]
 [132 175 198]]
Cumulative Product of Rows : 
[[    11    242   7986]
 [    44   2420 159720]
 [    77   7546 747054]]


### QUESTION 3
For this question, you are using Automobile Dataset. 

(i) Load the dataset into pandas dataframe.

In [15]:
import pandas as pd

file_path = "Automobile Dataset.csv"
df = pd.read_csv(file_path)


(ii) Display the first and last 5 rows.

In [16]:
print("Here is the first 5 rows:")
df.head(5)

Here is the first 5 rows:


index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0  
3             four         102               24  13950.0  
4             five         115               18  17450.0

In [17]:
df.tail(5)

index     company body-style  wheel-base  length engine-type  \
56     81  volkswagen      sedan        97.3   171.7         ohc   
57     82  volkswagen      sedan        97.3   171.7         ohc   
58     86  volkswagen      sedan        97.3   171.7         ohc   
59     87       volvo      sedan       104.3   188.8         ohc   
60     88       volvo      wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0

(iii) Print most expensive car’s company name and price.

In [21]:
max_price_index = df['price'].idxmax()
print(max_price_index)
most_expensive_company = df.loc[max_price_index, 'company']
most_expensive_price = df.loc[max_price_index, 'price']
print(f"The most expensive car is from {most_expensive_company} with a price of ${most_expensive_price}")


35
The most expensive car is from mercedes-benz with a price of $45400.0


(iv) Count total cars per company.

In [54]:
cars_per_company = df['company'].value_counts()
print(f"Total of cars per companies : \n{cars_per_company} ")

Total of cars per companies : 
company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: count, dtype: int64 


(v) Select only Toyota's cars. Find the average mileage and price of Toyota's cars.

In [55]:
toyota_cars = df[df['company'] == 'toyota']
average_mileage_toyota = toyota_cars['average-mileage'].mean()
average_price_toyota = toyota_cars['price'].mean()
print(f"Average mileage of Toyota's cars: {average_mileage_toyota:.2f} miles per gallon")
print(f"Average price of Toyota's cars: ${average_price_toyota:.2f}")

Average mileage of Toyota's cars: 28.71 miles per gallon
Average price of Toyota's cars: $8216.86


(vi) Sort all cars by Price and Horsepower column. List the expensive cars first.

In [56]:
sorted_cars = df.sort_values(by=['price', 'horsepower'], ascending=[False,False])
print(f"Cars are sorted by Price and Horsepower : \n{sorted_cars}")

Cars are sorted by Price and Horsepower : 
    index        company   body-style  wheel-base  length engine-type  \
35     47  mercedes-benz      hardtop       112.0   199.2        ohcv   
11     14            bmw        sedan       103.5   193.8         ohc   
34     46  mercedes-benz        sedan       120.9   208.1        ohcv   
46     62        porsche  convertible        89.5   168.9        ohcf   
12     15            bmw        sedan       110.0   197.0         ohc   
..    ...            ...          ...         ...     ...         ...   
27     36          mazda    hatchback        93.1   159.1         ohc   
13     16      chevrolet    hatchback        88.4   141.1           l   
47     63        porsche    hatchback        98.4   175.7       dohcv   
22     31          isuzu        sedan        94.5   155.9         ohc   
23     32          isuzu        sedan        94.5   155.9         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
35            eight 

(vii) Display all the maximum car price for each company.

In [57]:
max_price_per_company = df.groupby('company')['price'].max()
print(f"Maximum car price for individual companies : \n{max_price_per_company}")

Maximum car price for individual companies : 
company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64


### QUESTION 4


Given a data file, “emp_detail.csv” which consists of the employee’s details - name and department.

<br>
<img src="Figure 2.png", style="width: 250px";>

(i) Using Pandas library, read the CSV data file in Python into a variable ``emp_detail``.

In [58]:
import pandas as pd
file_path = 'emp_detail.csv'
emp_detail = pd.read_csv(file_path)

(ii) Display the first five rows of records of the data read in Step (i).

In [59]:
print(emp_detail.head(5))

      Name Department
0      ALI    FINANCE
1    AHMAD   STAFFING
2    CHONG    FINANCE
3   DARREN   STAFFING
4  JASMINE   STAFFING


(iii) Using the NumPy object of the attendance record created earlier:<br>
            a.	Convert the NumPy object into Data Frame, name it attendance.<br>
            b.	Merge the Data Frames ``emp_detail`` and attendance into a new data frame, name it ``emp_attendance``. 

In [23]:
attendance = pd.DataFrame(attendance_data, columns=['Day1', 'Day2', 'Day3', 'Day4', 'Day5', 'Day6', 'Day7', 'Day8', 'Day9', 'Day10', 'Day11', 'Day12', 'Day13', 'Day14'])
emp_detail = pd.read_csv('emp_detail.csv')
emp_attendance = pd.concat([emp_detail, attendance], axis=1)


print(f"Attendance DataFrame : \n{attendance}")
print(f"\nEmployee Details DataFrame : \n{emp_detail}")
print(f"\nMerged DataFrame (emp_attendance) :\n {emp_attendance}")

Attendance DataFrame : 
    Day1  Day2  Day3  Day4  Day5  Day6  Day7  Day8  Day9  Day10  Day11  Day12  \
0      1     1     1     1     1     1     1     1     1      1      1      1   
1      0     1     1     1     1     1     1     1     1      1      0      1   
2      1     1     1     1     1     1     0     1     0      0      1      1   
3      1     0     1     1     0     1     1     1     1      0      1      1   
4      1     0     0     0     1     1     1     1     0      0      0      0   
5      1     1     1     1     1     1     1     1     0      1      1      1   
6      1     1     1     0     0     1     1     1     0      1      1      0   
7      0     0     1     1     1     1     1     1     1      1      0      0   
8      0     1     1     1     1     0     1     0     1      1      0      1   
9      0     1     0     1     0     1     1     1     1      1      1      0   
10     0     0     0     1     1     1     1     1     1      1      1      1   
11  

(v) Add a column with name ``rate`` into the ``emp_attendance`` Data Frame that consists of the attendance rate / percentage the employee throughout the 14 days.

In [32]:
emp_attendance['total'] = emp_attendance[['Day1', 'Day2', 'Day3', 'Day4', 'Day5', 'Day6', 'Day7', 'Day8', 'Day9', 'Day10', 'Day11', 'Day12', 'Day13', 'Day14']].sum(axis=1)
print(f"Updated DataFrame (emp_attendance with total column) : \n{emp_attendance}")

emp_attendance['rate'] = (emp_attendance['total'] / 14) * 100
print(f"Updated DataFrame (emp_attendance with rate column) : \n{emp_attendance}")

Updated DataFrame (emp_attendance with total column) : 
       Name Department  Day1  Day2  Day3  Day4  Day5  Day6  Day7  Day8  Day9  \
0       ALI    FINANCE     1     1     1     1     1     1     1     1     1   
1     AHMAD   STAFFING     0     1     1     1     1     1     1     1     1   
2     CHONG    FINANCE     1     1     1     1     1     1     0     1     0   
3    DARREN   STAFFING     1     0     1     1     0     1     1     1     1   
4   JASMINE   STAFFING     1     0     0     0     1     1     1     1     0   
5    JOSHUA   STAFFING     1     1     1     1     1     1     1     1     0   
6     KELLY    FINANCE     1     1     1     0     0     1     1     1     0   
7       LIM    FINANCE     0     0     1     1     1     1     1     1     1   
8   NATASHA    FINANCE     0     1     1     1     1     0     1     0     1   
9      OMAR   STAFFING     0     1     0     1     0     1     1     1     1   
10   PATRIC   STAFFING     0     0     0     1     1     1     1

(vi) Consider following rules in classify the attendance:<br>
        a.	Rate > 90% : Good <br>
        b.	60% < Rate < 90% : Moderate <br>
        c.	Rate < 60% : Bad <br>
    Based on the grouping rule above, get the status for each of the staff and save the status in a new column ``status`` in the Data Frame.

In [26]:
emp_attendance['status'] = pd.cut(emp_attendance['rate'], bins=[0, 60, 90, 101], labels=['Bad', 'Moderate', 'Good'], right=False)
print(f"Updated DataFrame (emp_attendance with status column) :\n {emp_attendance}")

Updated DataFrame (emp_attendance with status column) :
        Name Department  Day1  Day2  Day3  Day4  Day5  Day6  Day7  Day8  Day9  \
0       ALI    FINANCE     1     1     1     1     1     1     1     1     1   
1     AHMAD   STAFFING     0     1     1     1     1     1     1     1     1   
2     CHONG    FINANCE     1     1     1     1     1     1     0     1     0   
3    DARREN   STAFFING     1     0     1     1     0     1     1     1     1   
4   JASMINE   STAFFING     1     0     0     0     1     1     1     1     0   
5    JOSHUA   STAFFING     1     1     1     1     1     1     1     1     0   
6     KELLY    FINANCE     1     1     1     0     0     1     1     1     0   
7       LIM    FINANCE     0     0     1     1     1     1     1     1     1   
8   NATASHA    FINANCE     0     1     1     1     1     0     1     0     1   
9      OMAR   STAFFING     0     1     0     1     0     1     1     1     1   
10   PATRIC   STAFFING     0     0     0     1     1     1     

(vii) Construct a function that returns the average attendance of all staff over the 14 days according to the department. 

In [33]:
def average_attendance_by_department(df):
    average_by_department = df.groupby('Department')['rate'].mean()
    return average_by_department


average_attendance = average_attendance_by_department(emp_attendance)
print(f"Average Attendance for all staff in each department :\n{average_attendance}")
print()



Average Attendance for all staff in each department :
Department
FINANCE     75.714286
STAFFING    75.000000
Name: rate, dtype: float64

